apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-backup-notification-2
  namespace: velero
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: velero-backup-notification-2
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: velero-backup-notification-2
    spec:
      containers:
      - env:
        - name: VELERO_NAMESPACE
          value: velero
        - name: RELEASE_NAMESPACE
          value: velero
        - name: NOTIFICATION_PREFIX
          value: '[Velero kuleuven]'
        - name: ENABLE_SLACK_NOTIFICATIONS
          value: "true"
        - name: SLACK_FAILURES_ONLY
          value: "true"
        - name: SLACK_USERNAME
          value: Velero
        - name: SLACK_WEBHOOK
          valueFrom:
            secretKeyRef:
              key: slack_webhook
              name: velero-backup-notification-secrets
        - name: SLACK_CHANNEL
          valueFrom:
            secretKeyRef:
              key: slack_channel
              name: velero-backup-notification-secrets
        - name: ENABLE_EMAIL_NOTIFICATIONS
          value: "false"
        - name: EMAIL_FAILURES_ONLY
          value: "true"
        - name: EMAIL_FROM_ADDRESS
          value: from@email.com
        - name: EMAIL_TO_ADDRESS
          value: to@email.com
        - name: EMAIL_SMTP_HOST
          valueFrom:
            secretKeyRef:
              key: email_smtp_host
              name: velero-backup-notification-secrets
        - name: EMAIL_SMTP_PORT
          valueFrom:
            secretKeyRef:
              key: email_smtp_port
              name: velero-backup-notification-secrets
        - name: EMAIL_SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              key: email_smtp_username
              name: velero-backup-notification-secrets
        - name: EMAIL_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: email_smtp_password
              name: velero-backup-notification-secrets
        - name: ENABLE_WEBHOOK_NOTIFICATIONS
          value: "false"
        - name: WEBHOOK_FAILURES_ONLY
          value: "false"
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              key: webhook_url
              name: velero-backup-notification-secrets
        image: ghcr.io/sequentech/velero-backup-notification:latest
        imagePullPolicy: Always
        name: velero-backup-notification
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - sysctl net.ipv4.tcp_keepalive_time=10 net.ipv4.tcp_keepalive_intvl=5 net.ipv4.tcp_keepalive_probes=3
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        name: fix-keepalive
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: velero
      serviceAccountName: velero
      terminationGracePeriodSeconds: 30
